### ISSUE TITLE
Southern Hemisphere Winter Sun positions between az = 270 and 360

### ISSUE THREAD

**Issue by astrophysically** [ccnmtl/astro-simulations#1787]
I came across some peculiar behavior when you try to model the position of the Sun on 30 June at latitude 63.4 degrees S. If you enter the time as a number and AM/PM in the time of day box, you can get a value for the azimuth that is completely incorrect. Advancing the clock a minute or two seems to snap it back into the appropriate behavior. A screenshot is included.
<img width="1131" alt="Screen Shot 2020-09-08 at 12 32 35 PM" src="https://user-images.githubusercontent.com/3966905/92504657-f4286100-f1d0-11ea-9ac3-fb0eb1854f40.png">

**Comment by nikolas** [comment]
Thanks for the report! This was a react state out of sync bug, that I just fixed yesterday, here: #1903
