### ISSUE TITLE
UTC is a good idea, but it breaks the local time functionality in the Solar Simulator

### ISSUE THREAD

**Issue by astrophysically** [ccnmtl/astro-simulations#1827]
Using the UTC tools is a good idea to avoid daylight savings, but unless the user is on the Prime Meridian, there will be timezone issues as the local time is what is displayed in the simulator and NOT UTC. For example, here in New York, noon on May 27 reads as 8:00 am which is the time that Noon is happening in London.

**Comment by nikolas** [comment]
My fix which broke things is reverted for now - I'll take a second look at this bug tomorrow.
